```{r Libraries}
library(Azimuth) # 0.5.0
library(glmGamPoi)
library(Seurat)
library(future)
# plan("multisession", workers = 1)
options(future.globals.maxSize = 120000 * 1024^2)
```


```{r Set Reference}
# for mouse
# dir_ref <- "/restricted/projectnb/crem-bioinfo/reference_data/REFERENCES/Azimuth/pansci_full/"
# for human lung
dir_ref <- "/restricted/projectnb/crem-bioinfo/reference_data/REFERENCES/Azimuth/lungref.SeuratData/azimuth/"
sc <- readRDS("/restricted/projectnb/crem-trainees/Kotton_Lab/Eitan/OutsidePaperObjects/Seurat/Habermann.rds")
rownames(sc@assays$RNA@meta.features) <- gsub(pattern = "_", replacement = "-", x = rownames(sc@assays$RNA@meta.features))
# sc@reductions <- list()
# sc <- JoinLayers(sc, assay = "RNA")
# sc <- SCTransform(sc, verbose = FALSE)
sc <- RunAzimuth(sc, reference = dir_ref)
```

```{r Set New Reference}
ref <- readRDS("/restricted/projectnb/crem-bioinfo/reference_data/REFERENCES/Azimuth/lungref.SeuratData/azimuth/ref.Rds")
habermann = readRDS("/restricted/projectnb/crem-trainees/Kotton_Lab/Eitan/OutsidePaperObjects/Seurat/Habermann.rds")
```
```{r Load}
Zack <- readRDS("/restricted/projectnb/crem-bioinfo/project_workspace/25_10_07_Darrell/calculations/William_Data/Zacharias_William_dataset.Rds")
Zack <- subset(Zack, subset = nFeature_RNA > 500 & nFeature_RNA < 5000 & percent_mito < 25)
Zack$RNA <- CreateAssayObject(counts = Zack@assays$RNA$counts)
Zack <- NormalizeData(Zack, normalization.method = "LogNormalize", scale.factor = 10000)
Zack <- FindVariableFeatures(Zack, selection.method = "vst", nfeatures = 2000)
Zack <- ScaleData(Zack, features = rownames(Zack))
Zack <- RunPCA(Zack, features = VariableFeatures(object = Zack))
ElbowPlot(Zack)

Zack <- FindNeighbors(Zack, dims = 1:15) # based on output from elbow plot
Zack <- FindClusters(Zack, resolution = 0.5)

Zack <- RunUMAP(Zack, dims = 1:10)
DimPlot(Zack, reduction = "umap")
VlnPlot(Zack, features = c("Krt5", "Trp63"))
cluster6.markers <- FindMarkers(Zack, ident.1 = 6, ident.2 = c(0, 1, 2, 3, 4, 5, 7, 8, 9, 10))
saveRDS(Zack, "/restricted/projectnb/crem-trainees/Kotton_Lab/Eitan/OutsidePaperObjects/Seurat/ZachariasReannotated.rds")
newAnnotations <- data.frame(seurat0.5=Zack$seurat_clusters, reannotation=Zack$celltypeEitan)
write.csv(newAnnotations, file="/restricted/projectnb/crem-trainees/Kotton_Lab/Eitan/OutsidePaperObjects/WIP/ZachariasAnnotations.csv")
```

